# Dependencies
# highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gasmen
tagline:          'Who's Your Gas Man?'
description:      'A brazen blog made by Gasmen, for Gasmen.  Apply now: <a href="https://www.instagram.com/wellturnyou/">@wellturnyou</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Gasman'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
